#!/bin/bash
set -e

# DEBUG_MODE=$INPUT_DEBUG_MODE \
# DEFAULT_BRANCH=$INPUT_DEFAULT_BRANCH \
# DEPRECATION_DAYS_LIMIT=$INPUT_DEPRECATION_DAYS_LIMIT \
# DEPRECATED_TAG=$INPUT_DEPRECATED_TAG \
# PR_CREATION_LIMIT=$INPUT_PR_CREATION_LIMIT \
# REGISTRY_REPO=$INPUT_REGISTRY_REPO \
# REMOVAL_DAYS_LIMIT=$INPUT_REMOVAL_DAYS_LIMIT \
# STACKS_DIR=$INPUT_STACKS_DIR \
python /maintainer.py