name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.1

      - name: Set up Python 3.10
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"

      - name: install depependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: qa check
        run: make qa

      - name: mypy check
        run: make mypy

      - name: Run tests
        run: make test
